//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.11 at 10:06:39 PM IST 
//


package org.editeur.onix.v21.shorts;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for List83.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="List83">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ALV"/>
 *     &lt;enumeration value="AMP"/>
 *     &lt;enumeration value="ANM"/>
 *     &lt;enumeration value="ASV"/>
 *     &lt;enumeration value="CEI"/>
 *     &lt;enumeration value="CEN"/>
 *     &lt;enumeration value="CEV"/>
 *     &lt;enumeration value="CNC"/>
 *     &lt;enumeration value="DDI"/>
 *     &lt;enumeration value="DDN"/>
 *     &lt;enumeration value="DOU"/>
 *     &lt;enumeration value="EIN"/>
 *     &lt;enumeration value="ESV"/>
 *     &lt;enumeration value="FBB"/>
 *     &lt;enumeration value="FRA"/>
 *     &lt;enumeration value="FRK"/>
 *     &lt;enumeration value="FRM"/>
 *     &lt;enumeration value="GDW"/>
 *     &lt;enumeration value="GEN"/>
 *     &lt;enumeration value="GNB"/>
 *     &lt;enumeration value="GPR"/>
 *     &lt;enumeration value="GRK"/>
 *     &lt;enumeration value="GRM"/>
 *     &lt;enumeration value="HBR"/>
 *     &lt;enumeration value="HCS"/>
 *     &lt;enumeration value="ICB"/>
 *     &lt;enumeration value="ILC"/>
 *     &lt;enumeration value="JER"/>
 *     &lt;enumeration value="KJV"/>
 *     &lt;enumeration value="KJT"/>
 *     &lt;enumeration value="LVB"/>
 *     &lt;enumeration value="LZZ"/>
 *     &lt;enumeration value="MSG"/>
 *     &lt;enumeration value="NAB"/>
 *     &lt;enumeration value="NAS"/>
 *     &lt;enumeration value="NAU"/>
 *     &lt;enumeration value="NBA"/>
 *     &lt;enumeration value="NBB"/>
 *     &lt;enumeration value="NBC"/>
 *     &lt;enumeration value="NBD"/>
 *     &lt;enumeration value="NBE"/>
 *     &lt;enumeration value="NBF"/>
 *     &lt;enumeration value="NBG"/>
 *     &lt;enumeration value="NBH"/>
 *     &lt;enumeration value="NBI"/>
 *     &lt;enumeration value="NCV"/>
 *     &lt;enumeration value="NEB"/>
 *     &lt;enumeration value="NGO"/>
 *     &lt;enumeration value="NIV"/>
 *     &lt;enumeration value="NIR"/>
 *     &lt;enumeration value="NJB"/>
 *     &lt;enumeration value="NKJ"/>
 *     &lt;enumeration value="NNK"/>
 *     &lt;enumeration value="NLV"/>
 *     &lt;enumeration value="NRS"/>
 *     &lt;enumeration value="NTV"/>
 *     &lt;enumeration value="NVB"/>
 *     &lt;enumeration value="NVD"/>
 *     &lt;enumeration value="NVI"/>
 *     &lt;enumeration value="PHP"/>
 *     &lt;enumeration value="REB"/>
 *     &lt;enumeration value="REV"/>
 *     &lt;enumeration value="RSV"/>
 *     &lt;enumeration value="RVL"/>
 *     &lt;enumeration value="SBB"/>
 *     &lt;enumeration value="SMK"/>
 *     &lt;enumeration value="TEV"/>
 *     &lt;enumeration value="TNI"/>
 *     &lt;enumeration value="ZZZ"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "List83")
@XmlEnum
public enum List83 {


    /**
     * Alberto Vaccari – Pontificio Istituto Biblico.
     * 
     */
    ALV,

    /**
     * A translation based on the American Standard Version and showing multiple options for the translation of ancient text. Published in full in 1965. Sponsored by the Lockman Foundation.
     * 
     */
    AMP,

    /**
     * Most popular Catholic Bible translation in Italian prior to the CEI translation in 1971.
     * 
     */
    ANM,

    /**
     * A 1901 translation using verbal equivalence techniques with the purpose of Americanizing the REV.
     * 
     */
    ASV,

    /**
     * Italian Episcopal Conference 1971 translation suitable for Italian Catholic liturgy. (Includes minor 1974 revision).
     * 
     */
    CEI,

    /**
     * New translation of the C.E.I. first published in 2008 – the version most widely used by the Italian Catholic Church.
     * 
     */
    CEN,

    /**
     * A translation completed in 1995 and sponsored by the American Bible Society under the leadership of Barclay Newman.
     * 
     */
    CEV,

    /**
     *  1968 Interfaith version promoted by the Italian Bible Society. Has a Catholic ‘imprimateur’, but its ecumenical approach has Jewish, Protestant and Christian Orthodox approval.
     * 
     */
    CNC,

    /**
     * Version based on original documents, edited by Giovanni Diodati in 1607, revised by Diodati in 1641 and again in 1894. It is the reference version for many Italian Protestants.
     * 
     */
    DDI,

    /**
     * Revision of the Diodati Bible dating to the 1990s, aiming at highest fidelity to original ancient Greek (New Testament) and Hebrew (Old Testament) texts.
     * 
     */
    DDN,

    /**
     * An early (1580-1609) English translation from the Latin Vulgate designed for Catholics and performed by George Martin.
     * 
     */
    DOU,

    /**
     * A German translation of the Bible for use in Roman Catholic churches.
     * 
     */
    EIN,

    /**
     * An update of the Revised Standard Version that makes ‘modest’ use of gender-free terminology.
     * 
     */
    ESV,

    /**
     * Finnish Bible translation.
     * 
     */
    FBB,

    /**
     * Finnish Bible translation.
     * 
     */
    FRA,

    /**
     * Finnish Bible translation.
     * 
     */
    FRK,

    /**
     * Finnish Bible translation.
     * 
     */
    FRM,

    /**
     * A 1995 translation by the World Bible Publishing Company using the English language in a manner to communicate to the late 20th century American.
     * 
     */
    GDW,

    /**
     * An early (1560) English version of the Bible translated by William Whittingham with strong Protestant leanings.
     * 
     */
    GEN,

    /**
     * A translation sponsored by the American Bible Society. The New Testament was first published (as “Today’s English Version” TEV) in 1966. The Old Testament was completed in 1976, and the whole was published as the “Good News Bible”.
     * 
     */
    GNB,

    /**
     * Version edited by E. Galbiati, A. Penna and P. Rossano, and published by UTET. This version, based on original texts, is rich in notes and has been used as the basis for CEI translation.
     * 
     */
    GPR,

    /**
     * New Testament text in an original Greek version.
     * 
     */
    GRK,

    /**
     * Richly annotated 1963 Version edited by S. Garofano and S. Rinaldi, and published by Marietti.
     * 
     */
    GRM,

    /**
     * Old Testament text in an original Hebrew version.
     * 
     */
    HBR,

    /**
     * Published by Broadman and Holman this translation rejects all forms of gender-neutral wording and is written with strong influences from the Southern Baptist perspective of biblical scholarship.
     * 
     */
    HCS,

    /**
     * A translation completed in 1986 targeting readability at the US third grade level.
     * 
     */
    ICB,

    /**
     * Interconfessional translation resulting from 1985 effort by Catholic and Protestant scholars, aimed at delivering an easy-to-understand message.
     * 
     */
    ILC,

    /**
     * A translation designed for English speaking Catholics based on the original languages. It is based on French as well as ancient texts and was first published in 1966.
     * 
     */
    JER,

    /**
     * A translation commissioned by King James I of England and first published in 1611.
     * 
     */
    KJV,

    /**
     * A verbal translation led by William Prindele. Published in 1994, it was designed to modernize the language of the King James Version based on Webster’s New International Dictionary, 2nd edition, unabridged.
     * 
     */
    KJT,

    /**
     * A paraphrase translation led by Kenneth N Taylor and first published in 1972.
     * 
     */
    LVB,

    /**
     *  1924 translation by Giovanni Luzzi, Professor at the Waldensian Faculty of Theology in Rome, who revised the 17th Century Diodati version.
     * 
     */
    LZZ,

    /**
     * A paraphrase translation of the New Testament by Eugene Peterson first published in 1993.
     * 
     */
    MSG,

    /**
     * A translation aimed at Catholic readers first published in its entirety in 1970. A revised New Testament was issued in 1986 as the 2nd Edition. The 3rd Edtion was published in 1991 with a revision to Psalms. The 4th Edition (also known as the New American Bible Revised Edition) was published in 2011, incorporating revisions to the Old Testament.
     * 
     */
    NAB,

    /**
     * A translation commissioned by the Lockman Foundation. The New Testament was published in 1960 followed by the entire Bible in 1971.
     * 
     */
    NAS,

    /**
     * A 1995 translation using more modern language than the NASB.
     * 
     */
    NAU,

    /**
     * Norwegian Bible translation.
     * 
     */
    NBA,

    /**
     * Norwegian Bible translation.
     * 
     */
    NBB,

    /**
     * Norwegian Bible translation.
     * 
     */
    NBC,

    /**
     * Norwegian Bible translation.
     * 
     */
    NBD,

    /**
     * Norwegian Bible translation.
     * 
     */
    NBE,

    /**
     * Norwegian Bible translation.
     * 
     */
    NBF,

    /**
     * Norwegian Bible translation.
     * 
     */
    NBG,

    /**
     * Norwegian Bible translation.
     * 
     */
    NBH,

    /**
     * Norwegian Bible translation.
     * 
     */
    NBI,

    /**
     * A translation inspired by the International Children’s version. First published by World Publishing in 1991.
     * 
     */
    NCV,

    /**
     * A translation first issued in 1961 (New Testament) and 1970 (complete Bible) as a result of a proposal at the 1946 General Assembly of the Church of Scotland.
     * 
     */
    NEB,

    /**
     * Norwegian Bible translation.
     * 
     */
    NGO,

    /**
     * A translation underwritten by Biblica (formerly the International Bible Society, and previously the New York Bible Society). The New Testament was published in 1973 followed by the entire Bible in 1978. The NIV text was revised in 1984 and again in 2011.
     * 
     */
    NIV,

    /**
     * A 1996 translation designed for people with limited literacy in English and based on the NIV.
     * 
     */
    NIR,

    /**
     * A revision of the Jerusalem Bible. First published in 1986.
     * 
     */
    NJB,

    /**
     * A version issued by Thomas Nelson Publishers in 1982-83 designed to update the language of the King James Version while maintaining the phrasing and rhythm and using the same sources as its predecessor.
     * 
     */
    NKJ,

    /**
     * Norwegian ‘nynorsk’ Bible translation.
     * 
     */
    NNK,

    /**
     * A translation sponsored by Tyndale House and first released in 1996. It is considered a revision and updating of the Living Bible.
     * 
     */
    NLV,

    /**
     * A revision of the Revised Standard based on ancient texts but updating language to American usage of the 1980s.
     * 
     */
    NRS,

    /**
     * A Spanish translation from the original Greek and Hebrew, sponsored by Tyndale House.
     * 
     */
    NTV,

    /**
     * Nuovissima version – a Catholic-oriented translation in modern Italian, edited by a group including Carlo Martini, Gianfranco Ravasi and Ugo Vanni and first published (in 48 volumes, 1967-1980) by Edizioni San Paolo.
     * 
     */
    NVB,

    /**
     * A Spanish translation from the original Greek and Hebrew, sponsored by the International Bible Society/Sociedad B\u00edblica Internacional.
     * 
     */
    NVD,

    /**
     * A Spanish translation underwritten by the International Bible Society.
     * 
     */
    NVI,

    /**
     * An idiomatic translation by J B Phillips, first completed in 1966.
     * 
     */
    PHP,

    /**
     * A 1989 revision of the NEB. A significant effort was made to reduce the British flavor present in the NEB.
     * 
     */
    REB,

    /**
     * The first major revision of the King James Version, the Revised Version incorporates insights from early manuscripts discovered between 1611 and 1870, and corrects readings in the KJV which nineteenth-century scholarship deemed mistaken. The New Testament was published in 1881, the Old Testament in 1885, and the Apocrypha in 1895.
     * 
     */
    REV,

    /**
     * A translation authorized by the National Council of Churches of Christ in the USA. The New Testament was published in 1946 followed by a complete Protestant canon in 1951.
     * 
     */
    RSV,

    /**
     * A Spanish translation based on the original texts.
     * 
     */
    RVL,

    /**
     * Swedish Bible translation.
     * 
     */
    SBB,

    /**
     * Norwegian ‘samisk’ Bible translation.
     * 
     */
    SMK,

    /**
     * A translation of the New Testament sponsored by the American Bible Society and first published in 1966. It was incorporated into the “Good News Bible” GNB in 1976.
     * 
     */
    TEV,

    /**
     * An updating of the New International Version. The New Testament was published in 2002, and the entire Bible in 2005. Superseded by the 2011 NIV update.
     * 
     */
    TNI,

    /**
     * Other translations not otherwise noted.
     * 
     */
    ZZZ;

    public String value() {
        return name();
    }

    public static List83 fromValue(String v) {
        return valueOf(v);
    }

}
