//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.11 at 10:06:33 PM IST 
//


package org.editeur.onix.v21.references;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for List17.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="List17">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="A01"/>
 *     &lt;enumeration value="A02"/>
 *     &lt;enumeration value="A03"/>
 *     &lt;enumeration value="A04"/>
 *     &lt;enumeration value="A05"/>
 *     &lt;enumeration value="A06"/>
 *     &lt;enumeration value="A07"/>
 *     &lt;enumeration value="A08"/>
 *     &lt;enumeration value="A09"/>
 *     &lt;enumeration value="A10"/>
 *     &lt;enumeration value="A11"/>
 *     &lt;enumeration value="A12"/>
 *     &lt;enumeration value="A13"/>
 *     &lt;enumeration value="A14"/>
 *     &lt;enumeration value="A15"/>
 *     &lt;enumeration value="A16"/>
 *     &lt;enumeration value="A17"/>
 *     &lt;enumeration value="A18"/>
 *     &lt;enumeration value="A19"/>
 *     &lt;enumeration value="A20"/>
 *     &lt;enumeration value="A21"/>
 *     &lt;enumeration value="A22"/>
 *     &lt;enumeration value="A23"/>
 *     &lt;enumeration value="A24"/>
 *     &lt;enumeration value="A25"/>
 *     &lt;enumeration value="A26"/>
 *     &lt;enumeration value="A27"/>
 *     &lt;enumeration value="A29"/>
 *     &lt;enumeration value="A30"/>
 *     &lt;enumeration value="A31"/>
 *     &lt;enumeration value="A32"/>
 *     &lt;enumeration value="A33"/>
 *     &lt;enumeration value="A34"/>
 *     &lt;enumeration value="A35"/>
 *     &lt;enumeration value="A36"/>
 *     &lt;enumeration value="A37"/>
 *     &lt;enumeration value="A38"/>
 *     &lt;enumeration value="A39"/>
 *     &lt;enumeration value="A40"/>
 *     &lt;enumeration value="A41"/>
 *     &lt;enumeration value="A42"/>
 *     &lt;enumeration value="A43"/>
 *     &lt;enumeration value="A44"/>
 *     &lt;enumeration value="A99"/>
 *     &lt;enumeration value="B01"/>
 *     &lt;enumeration value="B02"/>
 *     &lt;enumeration value="B03"/>
 *     &lt;enumeration value="B04"/>
 *     &lt;enumeration value="B05"/>
 *     &lt;enumeration value="B06"/>
 *     &lt;enumeration value="B07"/>
 *     &lt;enumeration value="B08"/>
 *     &lt;enumeration value="B09"/>
 *     &lt;enumeration value="B10"/>
 *     &lt;enumeration value="B11"/>
 *     &lt;enumeration value="B12"/>
 *     &lt;enumeration value="B13"/>
 *     &lt;enumeration value="B14"/>
 *     &lt;enumeration value="B15"/>
 *     &lt;enumeration value="B16"/>
 *     &lt;enumeration value="B17"/>
 *     &lt;enumeration value="B18"/>
 *     &lt;enumeration value="B19"/>
 *     &lt;enumeration value="B20"/>
 *     &lt;enumeration value="B21"/>
 *     &lt;enumeration value="B22"/>
 *     &lt;enumeration value="B23"/>
 *     &lt;enumeration value="B24"/>
 *     &lt;enumeration value="B25"/>
 *     &lt;enumeration value="B26"/>
 *     &lt;enumeration value="B99"/>
 *     &lt;enumeration value="C01"/>
 *     &lt;enumeration value="C02"/>
 *     &lt;enumeration value="C99"/>
 *     &lt;enumeration value="D01"/>
 *     &lt;enumeration value="D02"/>
 *     &lt;enumeration value="D03"/>
 *     &lt;enumeration value="D99"/>
 *     &lt;enumeration value="E01"/>
 *     &lt;enumeration value="E02"/>
 *     &lt;enumeration value="E03"/>
 *     &lt;enumeration value="E04"/>
 *     &lt;enumeration value="E05"/>
 *     &lt;enumeration value="E06"/>
 *     &lt;enumeration value="E07"/>
 *     &lt;enumeration value="E08"/>
 *     &lt;enumeration value="E09"/>
 *     &lt;enumeration value="E99"/>
 *     &lt;enumeration value="F01"/>
 *     &lt;enumeration value="F99"/>
 *     &lt;enumeration value="Z01"/>
 *     &lt;enumeration value="Z99"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "List17")
@XmlEnum
public enum List17 {


    /**
     * Author of a textual work.
     * 
     */
    @XmlEnumValue("A01")
    A_01("A01"),

    /**
     * With or as told to: ‘ghost’ author of a literary work.
     * 
     */
    @XmlEnumValue("A02")
    A_02("A02"),

    /**
     * Writer of screenplay or script (film or video).
     * 
     */
    @XmlEnumValue("A03")
    A_03("A03"),

    /**
     * Writer of libretto (opera): see also A31.
     * 
     */
    @XmlEnumValue("A04")
    A_04("A04"),

    /**
     * Author of lyrics (song): see also A31.
     * 
     */
    @XmlEnumValue("A05")
    A_05("A05"),

    /**
     * Composer of music.
     * 
     */
    @XmlEnumValue("A06")
    A_06("A06"),

    /**
     * Visual artist when named as the primary creator of, eg, a book of reproductions of artworks.
     * 
     */
    @XmlEnumValue("A07")
    A_07("A07"),

    /**
     * Photographer when named as the primary creator of, eg, a book of photographs.
     * 
     */
    @XmlEnumValue("A08")
    A_08("A08"),
    @XmlEnumValue("A09")
    A_09("A09"),
    @XmlEnumValue("A10")
    A_10("A10"),
    @XmlEnumValue("A11")
    A_11("A11"),

    /**
     * Artist when named as the creator of artwork which illustrates a text, or of the artwork of a graphic novel or comic book.
     * 
     */
    @XmlEnumValue("A12")
    A_12("A12"),

    /**
     * Photographer when named as the creator of photographs which illustrate a text.
     * 
     */
    @XmlEnumValue("A13")
    A_13("A13"),

    /**
     * Author of text which accompanies art reproductions or photographs, or which is part of a graphic novel or comic book.
     * 
     */
    @XmlEnumValue("A14")
    A_14("A14"),

    /**
     * Author of preface.
     * 
     */
    @XmlEnumValue("A15")
    A_15("A15"),

    /**
     * Author of prologue.
     * 
     */
    @XmlEnumValue("A16")
    A_16("A16"),

    /**
     * Author of summary.
     * 
     */
    @XmlEnumValue("A17")
    A_17("A17"),

    /**
     * Author of supplement.
     * 
     */
    @XmlEnumValue("A18")
    A_18("A18"),

    /**
     * Author of afterword.
     * 
     */
    @XmlEnumValue("A19")
    A_19("A19"),

    /**
     * Author of notes or annotations: see also A29.
     * 
     */
    @XmlEnumValue("A20")
    A_20("A20"),

    /**
     * Author of commentaries on the main text.
     * 
     */
    @XmlEnumValue("A21")
    A_21("A21"),

    /**
     * Author of epilogue.
     * 
     */
    @XmlEnumValue("A22")
    A_22("A22"),

    /**
     * Author of foreword.
     * 
     */
    @XmlEnumValue("A23")
    A_23("A23"),

    /**
     * Author of introduction: see also A29.
     * 
     */
    @XmlEnumValue("A24")
    A_24("A24"),

    /**
     * Author/compiler of footnotes.
     * 
     */
    @XmlEnumValue("A25")
    A_25("A25"),

    /**
     * Author of memoir accompanying main text.
     * 
     */
    @XmlEnumValue("A26")
    A_26("A26"),

    /**
     * Person who carried out experiments reported in the text.
     * 
     */
    @XmlEnumValue("A27")
    A_27("A27"),

    /**
     * Author of introduction and notes: see also A20 and A24.
     * 
     */
    @XmlEnumValue("A29")
    A_29("A29"),

    /**
     * Writer of computer programs ancillary to the text.
     * 
     */
    @XmlEnumValue("A30")
    A_30("A30"),

    /**
     * Author of the textual content of a musical drama: see also A04 and A05.
     * 
     */
    @XmlEnumValue("A31")
    A_31("A31"),

    /**
     * Author of additional contributions to the text.
     * 
     */
    @XmlEnumValue("A32")
    A_32("A32"),

    /**
     * Author of appendix.
     * 
     */
    @XmlEnumValue("A33")
    A_33("A33"),

    /**
     * Compiler of index.
     * 
     */
    @XmlEnumValue("A34")
    A_34("A34"),
    @XmlEnumValue("A35")
    A_35("A35"),

    /**
     * Use also for the cover artist of a graphic novel or comic book if named separately.
     * 
     */
    @XmlEnumValue("A36")
    A_36("A36"),

    /**
     * Responsible for preliminary work on which the work is based.
     * 
     */
    @XmlEnumValue("A37")
    A_37("A37"),

    /**
     * Author of the first edition (usually of a standard work) who is not an author of the current edition.
     * 
     */
    @XmlEnumValue("A38")
    A_38("A38"),

    /**
     * Maps drawn or otherwise contributed by.
     * 
     */
    @XmlEnumValue("A39")
    A_39("A39"),

    /**
     * When separate persons are named as having respectively drawn and colored artwork, eg for a graphic novel or comic book, use A12 for ‘drawn by’ and A40 for ‘colored by’.
     * 
     */
    @XmlEnumValue("A40")
    A_40("A40"),

    /**
     * Designer of pop-ups in a pop-up book, who may be different from the illustrator.
     * 
     */
    @XmlEnumValue("A41")
    A_41("A41"),

    /**
     * Use where a standard work is being continued by somebody other than the original author.
     * 
     */
    @XmlEnumValue("A42")
    A_42("A42"),
    @XmlEnumValue("A43")
    A_43("A43"),
    @XmlEnumValue("A44")
    A_44("A44"),

    /**
     * Other type of primary creator not specified above.
     * 
     */
    @XmlEnumValue("A99")
    A_99("A99"),
    @XmlEnumValue("B01")
    B_01("B01"),
    @XmlEnumValue("B02")
    B_02("B02"),
    @XmlEnumValue("B03")
    B_03("B03"),
    @XmlEnumValue("B04")
    B_04("B04"),
    @XmlEnumValue("B05")
    B_05("B05"),
    @XmlEnumValue("B06")
    B_06("B06"),
    @XmlEnumValue("B07")
    B_07("B07"),

    /**
     * This code applies where a translator has provided a commentary on issues relating to the translation. If the translator has also provided a commentary on the work itself, codes B06 and A21 should be used.
     * 
     */
    @XmlEnumValue("B08")
    B_08("B08"),

    /**
     * Name of a series editor when the product belongs to a series.
     * 
     */
    @XmlEnumValue("B09")
    B_09("B09"),
    @XmlEnumValue("B10")
    B_10("B10"),
    @XmlEnumValue("B11")
    B_11("B11"),
    @XmlEnumValue("B12")
    B_12("B12"),
    @XmlEnumValue("B13")
    B_13("B13"),
    @XmlEnumValue("B14")
    B_14("B14"),
    @XmlEnumValue("B15")
    B_15("B15"),
    @XmlEnumValue("B16")
    B_16("B16"),

    /**
     * Usually the founder editor of a serial publication: Begruendet von.
     * 
     */
    @XmlEnumValue("B17")
    B_17("B17"),
    @XmlEnumValue("B18")
    B_18("B18"),
    @XmlEnumValue("B19")
    B_19("B19"),

    /**
     * Use also for ‘advisory editor’.
     * 
     */
    @XmlEnumValue("B20")
    B_20("B20"),
    @XmlEnumValue("B21")
    B_21("B21"),
    @XmlEnumValue("B22")
    B_22("B22"),

    /**
     * In Europe, an expert editor who takes responsibility for the legal content of a collaborative law volume.
     * 
     */
    @XmlEnumValue("B23")
    B_23("B23"),

    /**
     * An editor who is responsible for establishing the text used in an edition of a literary work, where this is recognised as a distinctive role (in Spain, ‘editor literario’).
     * 
     */
    @XmlEnumValue("B24")
    B_24("B24"),
    @XmlEnumValue("B25")
    B_25("B25"),
    @XmlEnumValue("B26")
    B_26("B26"),

    /**
     * Other type of adaptation or editing not specified above.
     * 
     */
    @XmlEnumValue("B99")
    B_99("B99"),
    @XmlEnumValue("C01")
    C_01("C01"),
    @XmlEnumValue("C02")
    C_02("C02"),

    /**
     * Other type of compilation not specified above.
     * 
     */
    @XmlEnumValue("C99")
    C_99("C99"),
    @XmlEnumValue("D01")
    D_01("D01"),
    @XmlEnumValue("D02")
    D_02("D02"),

    /**
     * Conductor of a musical performance.
     * 
     */
    @XmlEnumValue("D03")
    D_03("D03"),

    /**
     * Other type of direction not specified above.
     * 
     */
    @XmlEnumValue("D99")
    D_99("D99"),
    @XmlEnumValue("E01")
    E_01("E01"),
    @XmlEnumValue("E02")
    E_02("E02"),
    @XmlEnumValue("E03")
    E_03("E03"),
    @XmlEnumValue("E04")
    E_04("E04"),

    /**
     * Singer etc.
     * 
     */
    @XmlEnumValue("E05")
    E_05("E05"),
    @XmlEnumValue("E06")
    E_06("E06"),

    /**
     * Reader of recorded text, as in an audiobook.
     * 
     */
    @XmlEnumValue("E07")
    E_07("E07"),

    /**
     * Name of a musical group in a performing role.
     * 
     */
    @XmlEnumValue("E08")
    E_08("E08"),

    /**
     * Of a speech, lecture etc.
     * 
     */
    @XmlEnumValue("E09")
    E_09("E09"),

    /**
     * Other type of performer not specified above: use for a recorded performance which does not fit a category above, eg a performance by a stand-up comedian.
     * 
     */
    @XmlEnumValue("E99")
    E_99("E99"),
    @XmlEnumValue("F01")
    F_01("F01"),

    /**
     * Other type of recording not specified above.
     * 
     */
    @XmlEnumValue("F99")
    F_99("F99"),

    /**
     * May be associated with any contributor role, and placement should therefore be controlled by contributor sequence numbering.
     * 
     */
    @XmlEnumValue("Z01")
    Z_01("Z01"),

    /**
     * Other creative responsibility not falling within A to F above.
     * 
     */
    @XmlEnumValue("Z99")
    Z_99("Z99");
    private final String value;

    List17(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static List17 fromValue(String v) {
        for (List17 c: List17 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
