//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.11 at 10:06:33 PM IST 
//


package org.editeur.onix.v21.references;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for List49.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="List49">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AU-CT"/>
 *     &lt;enumeration value="AU-NS"/>
 *     &lt;enumeration value="AU-NT"/>
 *     &lt;enumeration value="AU-QL"/>
 *     &lt;enumeration value="AU-SA"/>
 *     &lt;enumeration value="AU-TS"/>
 *     &lt;enumeration value="AU-VI"/>
 *     &lt;enumeration value="AU-WA"/>
 *     &lt;enumeration value="CA-AB"/>
 *     &lt;enumeration value="CA-BC"/>
 *     &lt;enumeration value="CA-MB"/>
 *     &lt;enumeration value="CA-NB"/>
 *     &lt;enumeration value="CA-NL"/>
 *     &lt;enumeration value="CA-NS"/>
 *     &lt;enumeration value="CA-NT"/>
 *     &lt;enumeration value="CA-NU"/>
 *     &lt;enumeration value="CA-ON"/>
 *     &lt;enumeration value="CA-PE"/>
 *     &lt;enumeration value="CA-QC"/>
 *     &lt;enumeration value="CA-SK"/>
 *     &lt;enumeration value="CA-YT"/>
 *     &lt;enumeration value="ES-CN"/>
 *     &lt;enumeration value="GB-AIR"/>
 *     &lt;enumeration value="GB-APS"/>
 *     &lt;enumeration value="GB-CHA"/>
 *     &lt;enumeration value="GB-ENG"/>
 *     &lt;enumeration value="GB-EWS"/>
 *     &lt;enumeration value="GB-IOM"/>
 *     &lt;enumeration value="GB-NIR"/>
 *     &lt;enumeration value="GB-SCT"/>
 *     &lt;enumeration value="GB-WLS"/>
 *     &lt;enumeration value="US-AK"/>
 *     &lt;enumeration value="US-AL"/>
 *     &lt;enumeration value="US-AR"/>
 *     &lt;enumeration value="US-AZ"/>
 *     &lt;enumeration value="US-CA"/>
 *     &lt;enumeration value="US-CO"/>
 *     &lt;enumeration value="US-CT"/>
 *     &lt;enumeration value="US-DC"/>
 *     &lt;enumeration value="US-DE"/>
 *     &lt;enumeration value="US-FL"/>
 *     &lt;enumeration value="US-GA"/>
 *     &lt;enumeration value="US-HI"/>
 *     &lt;enumeration value="US-IA"/>
 *     &lt;enumeration value="US-ID"/>
 *     &lt;enumeration value="US-IL"/>
 *     &lt;enumeration value="US-IN"/>
 *     &lt;enumeration value="US-KS"/>
 *     &lt;enumeration value="US-KY"/>
 *     &lt;enumeration value="US-LA"/>
 *     &lt;enumeration value="US-MA"/>
 *     &lt;enumeration value="US-MD"/>
 *     &lt;enumeration value="US-ME"/>
 *     &lt;enumeration value="US-MI"/>
 *     &lt;enumeration value="US-MN"/>
 *     &lt;enumeration value="US-MO"/>
 *     &lt;enumeration value="US-MS"/>
 *     &lt;enumeration value="US-MT"/>
 *     &lt;enumeration value="US-NC"/>
 *     &lt;enumeration value="US-ND"/>
 *     &lt;enumeration value="US-NE"/>
 *     &lt;enumeration value="US-NH"/>
 *     &lt;enumeration value="US-NJ"/>
 *     &lt;enumeration value="US-NM"/>
 *     &lt;enumeration value="US-NV"/>
 *     &lt;enumeration value="US-NY"/>
 *     &lt;enumeration value="US-OH"/>
 *     &lt;enumeration value="US-OK"/>
 *     &lt;enumeration value="US-OR"/>
 *     &lt;enumeration value="US-PA"/>
 *     &lt;enumeration value="US-RI"/>
 *     &lt;enumeration value="US-SC"/>
 *     &lt;enumeration value="US-SD"/>
 *     &lt;enumeration value="US-TN"/>
 *     &lt;enumeration value="US-TX"/>
 *     &lt;enumeration value="US-UT"/>
 *     &lt;enumeration value="US-VA"/>
 *     &lt;enumeration value="US-VT"/>
 *     &lt;enumeration value="US-WA"/>
 *     &lt;enumeration value="US-WI"/>
 *     &lt;enumeration value="US-WV"/>
 *     &lt;enumeration value="US-WY"/>
 *     &lt;enumeration value="ECZ"/>
 *     &lt;enumeration value="ROW"/>
 *     &lt;enumeration value="WORLD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "List49")
@XmlEnum
public enum List49 {

    @XmlEnumValue("AU-CT")
    AU_CT("AU-CT"),
    @XmlEnumValue("AU-NS")
    AU_NS("AU-NS"),
    @XmlEnumValue("AU-NT")
    AU_NT("AU-NT"),
    @XmlEnumValue("AU-QL")
    AU_QL("AU-QL"),
    @XmlEnumValue("AU-SA")
    AU_SA("AU-SA"),
    @XmlEnumValue("AU-TS")
    AU_TS("AU-TS"),
    @XmlEnumValue("AU-VI")
    AU_VI("AU-VI"),
    @XmlEnumValue("AU-WA")
    AU_WA("AU-WA"),
    @XmlEnumValue("CA-AB")
    CA_AB("CA-AB"),
    @XmlEnumValue("CA-BC")
    CA_BC("CA-BC"),
    @XmlEnumValue("CA-MB")
    CA_MB("CA-MB"),
    @XmlEnumValue("CA-NB")
    CA_NB("CA-NB"),
    @XmlEnumValue("CA-NL")
    CA_NL("CA-NL"),
    @XmlEnumValue("CA-NS")
    CA_NS("CA-NS"),
    @XmlEnumValue("CA-NT")
    CA_NT("CA-NT"),
    @XmlEnumValue("CA-NU")
    CA_NU("CA-NU"),
    @XmlEnumValue("CA-ON")
    CA_ON("CA-ON"),
    @XmlEnumValue("CA-PE")
    CA_PE("CA-PE"),
    @XmlEnumValue("CA-QC")
    CA_QC("CA-QC"),
    @XmlEnumValue("CA-SK")
    CA_SK("CA-SK"),
    @XmlEnumValue("CA-YT")
    CA_YT("CA-YT"),
    @XmlEnumValue("ES-CN")
    ES_CN("ES-CN"),

    /**
     * Airside outlets at UK international airports only.
     * 
     */
    @XmlEnumValue("GB-AIR")
    GB_AIR("GB-AIR"),

    /**
     * All UK airports, including both airside and other outlets.
     * 
     */
    @XmlEnumValue("GB-APS")
    GB_APS("GB-APS"),

    /**
     * DEPRECATED, replaced by country codes GG – Guernsey, and JE – Jersey.
     * 
     */
    @XmlEnumValue("GB-CHA")
    GB_CHA("GB-CHA"),
    @XmlEnumValue("GB-ENG")
    GB_ENG("GB-ENG"),

    /**
     * UK excluding Northern Ireland.
     * 
     */
    @XmlEnumValue("GB-EWS")
    GB_EWS("GB-EWS"),

    /**
     * DEPRECATED, replaced by country code IM – Isle of Man.
     * 
     */
    @XmlEnumValue("GB-IOM")
    GB_IOM("GB-IOM"),
    @XmlEnumValue("GB-NIR")
    GB_NIR("GB-NIR"),
    @XmlEnumValue("GB-SCT")
    GB_SCT("GB-SCT"),
    @XmlEnumValue("GB-WLS")
    GB_WLS("GB-WLS"),
    @XmlEnumValue("US-AK")
    US_AK("US-AK"),
    @XmlEnumValue("US-AL")
    US_AL("US-AL"),
    @XmlEnumValue("US-AR")
    US_AR("US-AR"),
    @XmlEnumValue("US-AZ")
    US_AZ("US-AZ"),
    @XmlEnumValue("US-CA")
    US_CA("US-CA"),
    @XmlEnumValue("US-CO")
    US_CO("US-CO"),
    @XmlEnumValue("US-CT")
    US_CT("US-CT"),
    @XmlEnumValue("US-DC")
    US_DC("US-DC"),
    @XmlEnumValue("US-DE")
    US_DE("US-DE"),
    @XmlEnumValue("US-FL")
    US_FL("US-FL"),
    @XmlEnumValue("US-GA")
    US_GA("US-GA"),
    @XmlEnumValue("US-HI")
    US_HI("US-HI"),
    @XmlEnumValue("US-IA")
    US_IA("US-IA"),
    @XmlEnumValue("US-ID")
    US_ID("US-ID"),
    @XmlEnumValue("US-IL")
    US_IL("US-IL"),
    @XmlEnumValue("US-IN")
    US_IN("US-IN"),
    @XmlEnumValue("US-KS")
    US_KS("US-KS"),
    @XmlEnumValue("US-KY")
    US_KY("US-KY"),
    @XmlEnumValue("US-LA")
    US_LA("US-LA"),
    @XmlEnumValue("US-MA")
    US_MA("US-MA"),
    @XmlEnumValue("US-MD")
    US_MD("US-MD"),
    @XmlEnumValue("US-ME")
    US_ME("US-ME"),
    @XmlEnumValue("US-MI")
    US_MI("US-MI"),
    @XmlEnumValue("US-MN")
    US_MN("US-MN"),
    @XmlEnumValue("US-MO")
    US_MO("US-MO"),
    @XmlEnumValue("US-MS")
    US_MS("US-MS"),
    @XmlEnumValue("US-MT")
    US_MT("US-MT"),
    @XmlEnumValue("US-NC")
    US_NC("US-NC"),
    @XmlEnumValue("US-ND")
    US_ND("US-ND"),
    @XmlEnumValue("US-NE")
    US_NE("US-NE"),
    @XmlEnumValue("US-NH")
    US_NH("US-NH"),
    @XmlEnumValue("US-NJ")
    US_NJ("US-NJ"),
    @XmlEnumValue("US-NM")
    US_NM("US-NM"),
    @XmlEnumValue("US-NV")
    US_NV("US-NV"),
    @XmlEnumValue("US-NY")
    US_NY("US-NY"),
    @XmlEnumValue("US-OH")
    US_OH("US-OH"),
    @XmlEnumValue("US-OK")
    US_OK("US-OK"),
    @XmlEnumValue("US-OR")
    US_OR("US-OR"),
    @XmlEnumValue("US-PA")
    US_PA("US-PA"),
    @XmlEnumValue("US-RI")
    US_RI("US-RI"),
    @XmlEnumValue("US-SC")
    US_SC("US-SC"),
    @XmlEnumValue("US-SD")
    US_SD("US-SD"),
    @XmlEnumValue("US-TN")
    US_TN("US-TN"),
    @XmlEnumValue("US-TX")
    US_TX("US-TX"),
    @XmlEnumValue("US-UT")
    US_UT("US-UT"),
    @XmlEnumValue("US-VA")
    US_VA("US-VA"),
    @XmlEnumValue("US-VT")
    US_VT("US-VT"),
    @XmlEnumValue("US-WA")
    US_WA("US-WA"),
    @XmlEnumValue("US-WI")
    US_WI("US-WI"),
    @XmlEnumValue("US-WV")
    US_WV("US-WV"),
    @XmlEnumValue("US-WY")
    US_WY("US-WY"),

    /**
     * Countries geographically within continental Europe which use the Euro as their sole currency. At the time of writing, this is a synonym for “AT BE CY EE FI FR DE ES GR IE IT LU MT NL PT SI SK” (the official Eurozone 17), plus “AD MC SM VA ME” (other Euro-using countries in continental Europe). Note some other territories using the Euro, but outside continental Europe are excluded from this list, and may need to be specified separately. Only valid in ONIX 3, and only within Block 6.
     * 
     */
    ECZ("ECZ"),

    /**
     * World except as otherwise specified. NOT USED in ONIX 3.
     * 
     */
    ROW("ROW"),
    WORLD("WORLD");
    private final String value;

    List49(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static List49 fromValue(String v) {
        for (List49 c: List49 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
