//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.11 at 10:06:33 PM IST 
//


package org.editeur.onix.v21.references;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.editeur.org/onix/2.1/reference}PriceTypeCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/2.1/reference}PriceQualifier" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/2.1/reference}PriceTypeDescription" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/2.1/reference}PricePer" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/2.1/reference}MinimumOrderQuantity" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/2.1/reference}BatchBonus" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/2.1/reference}ClassOfTrade" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/2.1/reference}BICDiscountGroupCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/2.1/reference}DiscountCoded" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/2.1/reference}DiscountPercent" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/2.1/reference}PriceStatus" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/2.1/reference}PriceAmount"/>
 *         &lt;element ref="{http://www.editeur.org/onix/2.1/reference}CurrencyCode" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;choice>
 *             &lt;sequence>
 *               &lt;element ref="{http://www.editeur.org/onix/2.1/reference}CountryCode" maxOccurs="unbounded"/>
 *               &lt;element ref="{http://www.editeur.org/onix/2.1/reference}Territory" minOccurs="0"/>
 *             &lt;/sequence>
 *             &lt;element ref="{http://www.editeur.org/onix/2.1/reference}Territory"/>
 *           &lt;/choice>
 *           &lt;element ref="{http://www.editeur.org/onix/2.1/reference}CountryExcluded" minOccurs="0"/>
 *           &lt;element ref="{http://www.editeur.org/onix/2.1/reference}TerritoryExcluded" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{http://www.editeur.org/onix/2.1/reference}TaxRateCode1"/>
 *           &lt;element ref="{http://www.editeur.org/onix/2.1/reference}TaxRatePercent1" minOccurs="0"/>
 *           &lt;element ref="{http://www.editeur.org/onix/2.1/reference}TaxableAmount1" minOccurs="0"/>
 *           &lt;element ref="{http://www.editeur.org/onix/2.1/reference}TaxAmount1" minOccurs="0"/>
 *           &lt;sequence minOccurs="0">
 *             &lt;element ref="{http://www.editeur.org/onix/2.1/reference}TaxRateCode2"/>
 *             &lt;element ref="{http://www.editeur.org/onix/2.1/reference}TaxRatePercent2" minOccurs="0"/>
 *             &lt;element ref="{http://www.editeur.org/onix/2.1/reference}TaxableAmount2" minOccurs="0"/>
 *             &lt;element ref="{http://www.editeur.org/onix/2.1/reference}TaxAmount2" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/sequence>
 *         &lt;element ref="{http://www.editeur.org/onix/2.1/reference}PriceEffectiveFrom" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/2.1/reference}PriceEffectiveUntil" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.editeur.org/onix/2.1/reference}generalAttributes"/>
 *       &lt;attribute name="refname" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" fixed="Price" />
 *       &lt;attribute name="shortname" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" fixed="price" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "Price")
public class Price {

    @XmlElementRefs({
        @XmlElementRef(name = "PriceEffectiveFrom", namespace = "http://www.editeur.org/onix/2.1/reference", type = PriceEffectiveFrom.class, required = false),
        @XmlElementRef(name = "PriceQualifier", namespace = "http://www.editeur.org/onix/2.1/reference", type = PriceQualifier.class, required = false),
        @XmlElementRef(name = "TaxRateCode1", namespace = "http://www.editeur.org/onix/2.1/reference", type = TaxRateCode1 .class, required = false),
        @XmlElementRef(name = "CountryExcluded", namespace = "http://www.editeur.org/onix/2.1/reference", type = CountryExcluded.class, required = false),
        @XmlElementRef(name = "TaxRatePercent1", namespace = "http://www.editeur.org/onix/2.1/reference", type = TaxRatePercent1 .class, required = false),
        @XmlElementRef(name = "TaxAmount1", namespace = "http://www.editeur.org/onix/2.1/reference", type = TaxAmount1 .class, required = false),
        @XmlElementRef(name = "TaxableAmount2", namespace = "http://www.editeur.org/onix/2.1/reference", type = TaxableAmount2 .class, required = false),
        @XmlElementRef(name = "BatchBonus", namespace = "http://www.editeur.org/onix/2.1/reference", type = BatchBonus.class, required = false),
        @XmlElementRef(name = "PriceAmount", namespace = "http://www.editeur.org/onix/2.1/reference", type = PriceAmount.class, required = false),
        @XmlElementRef(name = "Territory", namespace = "http://www.editeur.org/onix/2.1/reference", type = Territory.class, required = false),
        @XmlElementRef(name = "DiscountCoded", namespace = "http://www.editeur.org/onix/2.1/reference", type = DiscountCoded.class, required = false),
        @XmlElementRef(name = "ClassOfTrade", namespace = "http://www.editeur.org/onix/2.1/reference", type = ClassOfTrade.class, required = false),
        @XmlElementRef(name = "CurrencyCode", namespace = "http://www.editeur.org/onix/2.1/reference", type = CurrencyCode.class, required = false),
        @XmlElementRef(name = "BICDiscountGroupCode", namespace = "http://www.editeur.org/onix/2.1/reference", type = BICDiscountGroupCode.class, required = false),
        @XmlElementRef(name = "PriceEffectiveUntil", namespace = "http://www.editeur.org/onix/2.1/reference", type = PriceEffectiveUntil.class, required = false),
        @XmlElementRef(name = "TerritoryExcluded", namespace = "http://www.editeur.org/onix/2.1/reference", type = TerritoryExcluded.class, required = false),
        @XmlElementRef(name = "CountryCode", namespace = "http://www.editeur.org/onix/2.1/reference", type = CountryCode.class, required = false),
        @XmlElementRef(name = "PriceStatus", namespace = "http://www.editeur.org/onix/2.1/reference", type = PriceStatus.class, required = false),
        @XmlElementRef(name = "TaxRateCode2", namespace = "http://www.editeur.org/onix/2.1/reference", type = TaxRateCode2 .class, required = false),
        @XmlElementRef(name = "TaxableAmount1", namespace = "http://www.editeur.org/onix/2.1/reference", type = TaxableAmount1 .class, required = false),
        @XmlElementRef(name = "MinimumOrderQuantity", namespace = "http://www.editeur.org/onix/2.1/reference", type = MinimumOrderQuantity.class, required = false),
        @XmlElementRef(name = "PricePer", namespace = "http://www.editeur.org/onix/2.1/reference", type = PricePer.class, required = false),
        @XmlElementRef(name = "PriceTypeCode", namespace = "http://www.editeur.org/onix/2.1/reference", type = PriceTypeCode.class, required = false),
        @XmlElementRef(name = "DiscountPercent", namespace = "http://www.editeur.org/onix/2.1/reference", type = DiscountPercent.class, required = false),
        @XmlElementRef(name = "TaxRatePercent2", namespace = "http://www.editeur.org/onix/2.1/reference", type = TaxRatePercent2 .class, required = false),
        @XmlElementRef(name = "TaxAmount2", namespace = "http://www.editeur.org/onix/2.1/reference", type = TaxAmount2 .class, required = false),
        @XmlElementRef(name = "PriceTypeDescription", namespace = "http://www.editeur.org/onix/2.1/reference", type = PriceTypeDescription.class, required = false)
    })
    protected List<java.lang.Object> content;
    @XmlAttribute(name = "refname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String refname;
    @XmlAttribute(name = "shortname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String shortname;
    @XmlAttribute(name = "textformat")
    protected String textformat;
    @XmlAttribute(name = "textcase")
    protected String textcase;
    @XmlAttribute(name = "language")
    protected List74 language;
    @XmlAttribute(name = "transliteration")
    protected List138 transliteration;
    @XmlAttribute(name = "datestamp")
    protected String datestamp;
    @XmlAttribute(name = "sourcetype")
    protected String sourcetype;
    @XmlAttribute(name = "sourcename")
    protected String sourcename;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "Territory" is used by two different parts of a schema. See: 
     * line 3514 of file:/C:/DEV/Projects/Jonix/onix_doc/v2.1/ONIX_BookProduct_Release2.1_reference.xsd
     * line 3512 of file:/C:/DEV/Projects/Jonix/onix_doc/v2.1/ONIX_BookProduct_Release2.1_reference.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PriceEffectiveFrom }
     * {@link PriceQualifier }
     * {@link TaxRateCode1 }
     * {@link CountryExcluded }
     * {@link TaxRatePercent1 }
     * {@link TaxAmount1 }
     * {@link TaxableAmount2 }
     * {@link BatchBonus }
     * {@link PriceAmount }
     * {@link Territory }
     * {@link DiscountCoded }
     * {@link ClassOfTrade }
     * {@link CurrencyCode }
     * {@link BICDiscountGroupCode }
     * {@link PriceEffectiveUntil }
     * {@link TerritoryExcluded }
     * {@link CountryCode }
     * {@link PriceStatus }
     * {@link TaxRateCode2 }
     * {@link TaxableAmount1 }
     * {@link MinimumOrderQuantity }
     * {@link PricePer }
     * {@link PriceTypeCode }
     * {@link DiscountPercent }
     * {@link TaxRatePercent2 }
     * {@link TaxAmount2 }
     * {@link PriceTypeDescription }
     * 
     * 
     */
    public List<java.lang.Object> getContent() {
        if (content == null) {
            content = new ArrayList<java.lang.Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the refname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefname() {
        if (refname == null) {
            return "Price";
        } else {
            return refname;
        }
    }

    /**
     * Sets the value of the refname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefname(String value) {
        this.refname = value;
    }

    /**
     * Gets the value of the shortname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortname() {
        if (shortname == null) {
            return "price";
        } else {
            return shortname;
        }
    }

    /**
     * Sets the value of the shortname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortname(String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the textformat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextformat() {
        if (textformat == null) {
            return "00";
        } else {
            return textformat;
        }
    }

    /**
     * Sets the value of the textformat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextformat(String value) {
        this.textformat = value;
    }

    /**
     * Gets the value of the textcase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextcase() {
        if (textcase == null) {
            return "00";
        } else {
            return textcase;
        }
    }

    /**
     * Sets the value of the textcase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextcase(String value) {
        this.textcase = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link List74 }
     *     
     */
    public List74 getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link List74 }
     *     
     */
    public void setLanguage(List74 value) {
        this.language = value;
    }

    /**
     * Gets the value of the transliteration property.
     * 
     * @return
     *     possible object is
     *     {@link List138 }
     *     
     */
    public List138 getTransliteration() {
        return transliteration;
    }

    /**
     * Sets the value of the transliteration property.
     * 
     * @param value
     *     allowed object is
     *     {@link List138 }
     *     
     */
    public void setTransliteration(List138 value) {
        this.transliteration = value;
    }

    /**
     * Gets the value of the datestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatestamp() {
        return datestamp;
    }

    /**
     * Sets the value of the datestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatestamp(String value) {
        this.datestamp = value;
    }

    /**
     * Gets the value of the sourcetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcetype() {
        if (sourcetype == null) {
            return "00";
        } else {
            return sourcetype;
        }
    }

    /**
     * Sets the value of the sourcetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcetype(String value) {
        this.sourcetype = value;
    }

    /**
     * Gets the value of the sourcename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcename() {
        return sourcename;
    }

    /**
     * Sets the value of the sourcename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcename(String value) {
        this.sourcename = value;
    }

}
