//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 09:12:45 AM IST 
//


package org.editeur.onix.v30.shorts;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}b284" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}textitem"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}b288" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}b289" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}titledetail" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}contributor" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}subject" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}nameassubject" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}textcontent" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}citedcontent" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}supportingresource" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}relatedwork" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://ns.editeur.org/onix/3.0/short}generalAttributes"/>
 *       &lt;attribute name="refname">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="ContentItem"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="shortname">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="contentitem"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "b284",
    "textitem",
    "b288",
    "b289",
    "titledetail",
    "contributor",
    "subject",
    "nameassubject",
    "textcontent",
    "citedcontent",
    "supportingresource",
    "relatedwork"
})
@XmlRootElement(name = "contentitem")
public class Contentitem {

    protected B284 b284;
    @XmlElement(required = true)
    protected Textitem textitem;
    protected B288 b288;
    protected B289 b289;
    protected List<Titledetail> titledetail;
    protected List<Contributor> contributor;
    protected List<Subject> subject;
    protected List<Nameassubject> nameassubject;
    protected List<Textcontent> textcontent;
    protected List<Citedcontent> citedcontent;
    protected List<Supportingresource> supportingresource;
    protected List<Relatedwork> relatedwork;
    @XmlAttribute(name = "refname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String refname;
    @XmlAttribute(name = "shortname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String shortname;
    @XmlAttribute(name = "datestamp")
    protected String datestamp;
    @XmlAttribute(name = "sourcetype")
    protected String sourcetype;
    @XmlAttribute(name = "sourcename")
    @XmlSchemaType(name = "anySimpleType")
    protected String sourcename;

    /**
     * Gets the value of the b284 property.
     * 
     * @return
     *     possible object is
     *     {@link B284 }
     *     
     */
    public B284 getB284() {
        return b284;
    }

    /**
     * Sets the value of the b284 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B284 }
     *     
     */
    public void setB284(B284 value) {
        this.b284 = value;
    }

    /**
     * Gets the value of the textitem property.
     * 
     * @return
     *     possible object is
     *     {@link Textitem }
     *     
     */
    public Textitem getTextitem() {
        return textitem;
    }

    /**
     * Sets the value of the textitem property.
     * 
     * @param value
     *     allowed object is
     *     {@link Textitem }
     *     
     */
    public void setTextitem(Textitem value) {
        this.textitem = value;
    }

    /**
     * Gets the value of the b288 property.
     * 
     * @return
     *     possible object is
     *     {@link B288 }
     *     
     */
    public B288 getB288() {
        return b288;
    }

    /**
     * Sets the value of the b288 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B288 }
     *     
     */
    public void setB288(B288 value) {
        this.b288 = value;
    }

    /**
     * Gets the value of the b289 property.
     * 
     * @return
     *     possible object is
     *     {@link B289 }
     *     
     */
    public B289 getB289() {
        return b289;
    }

    /**
     * Sets the value of the b289 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B289 }
     *     
     */
    public void setB289(B289 value) {
        this.b289 = value;
    }

    /**
     * Gets the value of the titledetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the titledetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitledetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Titledetail }
     * 
     * 
     */
    public List<Titledetail> getTitledetail() {
        if (titledetail == null) {
            titledetail = new ArrayList<Titledetail>();
        }
        return this.titledetail;
    }

    /**
     * Gets the value of the contributor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contributor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContributor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Contributor }
     * 
     * 
     */
    public List<Contributor> getContributor() {
        if (contributor == null) {
            contributor = new ArrayList<Contributor>();
        }
        return this.contributor;
    }

    /**
     * Gets the value of the subject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Subject }
     * 
     * 
     */
    public List<Subject> getSubject() {
        if (subject == null) {
            subject = new ArrayList<Subject>();
        }
        return this.subject;
    }

    /**
     * Gets the value of the nameassubject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameassubject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNameassubject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Nameassubject }
     * 
     * 
     */
    public List<Nameassubject> getNameassubject() {
        if (nameassubject == null) {
            nameassubject = new ArrayList<Nameassubject>();
        }
        return this.nameassubject;
    }

    /**
     * Gets the value of the textcontent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the textcontent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTextcontent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Textcontent }
     * 
     * 
     */
    public List<Textcontent> getTextcontent() {
        if (textcontent == null) {
            textcontent = new ArrayList<Textcontent>();
        }
        return this.textcontent;
    }

    /**
     * Gets the value of the citedcontent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the citedcontent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCitedcontent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Citedcontent }
     * 
     * 
     */
    public List<Citedcontent> getCitedcontent() {
        if (citedcontent == null) {
            citedcontent = new ArrayList<Citedcontent>();
        }
        return this.citedcontent;
    }

    /**
     * Gets the value of the supportingresource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportingresource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportingresource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Supportingresource }
     * 
     * 
     */
    public List<Supportingresource> getSupportingresource() {
        if (supportingresource == null) {
            supportingresource = new ArrayList<Supportingresource>();
        }
        return this.supportingresource;
    }

    /**
     * Gets the value of the relatedwork property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedwork property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedwork().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Relatedwork }
     * 
     * 
     */
    public List<Relatedwork> getRelatedwork() {
        if (relatedwork == null) {
            relatedwork = new ArrayList<Relatedwork>();
        }
        return this.relatedwork;
    }

    /**
     * Gets the value of the refname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefname() {
        return refname;
    }

    /**
     * Sets the value of the refname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefname(String value) {
        this.refname = value;
    }

    /**
     * Gets the value of the shortname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortname(String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the datestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatestamp() {
        return datestamp;
    }

    /**
     * Sets the value of the datestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatestamp(String value) {
        this.datestamp = value;
    }

    /**
     * Gets the value of the sourcetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcetype() {
        return sourcetype;
    }

    /**
     * Sets the value of the sourcetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcetype(String value) {
        this.sourcetype = value;
    }

    /**
     * Gets the value of the sourcename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcename() {
        return sourcename;
    }

    /**
     * Sets the value of the sourcename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcename(String value) {
        this.sourcename = value;
    }

}
