//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 09:12:45 AM IST 
//


package org.editeur.onix.v30.shorts;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}b034" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}b035" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}x412" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}x413" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}x414" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}nameidentifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}b036" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}b037" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{http://ns.editeur.org/onix/3.0/short}b038" minOccurs="0"/>
 *           &lt;element ref="{http://ns.editeur.org/onix/3.0/short}b039" minOccurs="0"/>
 *           &lt;element ref="{http://ns.editeur.org/onix/3.0/short}b247" minOccurs="0"/>
 *           &lt;element ref="{http://ns.editeur.org/onix/3.0/short}b040"/>
 *           &lt;element ref="{http://ns.editeur.org/onix/3.0/short}b041" minOccurs="0"/>
 *           &lt;element ref="{http://ns.editeur.org/onix/3.0/short}b248" minOccurs="0"/>
 *           &lt;element ref="{http://ns.editeur.org/onix/3.0/short}b042" minOccurs="0"/>
 *           &lt;element ref="{http://ns.editeur.org/onix/3.0/short}b043" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}b047" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}x443" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}alternativename" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}contributordate" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}professionalaffiliation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}b044" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}website" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}b048" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}b249" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}contributorplace" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://ns.editeur.org/onix/3.0/short}generalAttributes"/>
 *       &lt;attribute name="refname">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="Contributor"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="shortname">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="contributor"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "b034",
    "b035",
    "x412",
    "x413",
    "x414",
    "nameidentifier",
    "b036",
    "b037",
    "b038",
    "b039",
    "b247",
    "b040",
    "b041",
    "b248",
    "b042",
    "b043",
    "b047",
    "x443",
    "alternativename",
    "contributordate",
    "professionalaffiliation",
    "b044",
    "website",
    "b048",
    "b249",
    "contributorplace"
})
@XmlRootElement(name = "contributor")
public class Contributor {

    protected B034 b034;
    @XmlElement(required = true)
    protected List<B035> b035;
    protected List<X412> x412;
    protected List<X413> x413;
    protected X414 x414;
    protected List<Nameidentifier> nameidentifier;
    protected B036 b036;
    protected B037 b037;
    protected B038 b038;
    protected B039 b039;
    protected B247 b247;
    protected B040 b040;
    protected B041 b041;
    protected B248 b248;
    protected B042 b042;
    protected B043 b043;
    protected B047 b047;
    protected X443 x443;
    protected List<Alternativename> alternativename;
    protected List<Contributordate> contributordate;
    protected List<Professionalaffiliation> professionalaffiliation;
    protected List<B044> b044;
    protected List<Website> website;
    protected List<B048> b048;
    protected B249 b249;
    protected List<Contributorplace> contributorplace;
    @XmlAttribute(name = "refname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String refname;
    @XmlAttribute(name = "shortname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String shortname;
    @XmlAttribute(name = "datestamp")
    protected String datestamp;
    @XmlAttribute(name = "sourcetype")
    protected String sourcetype;
    @XmlAttribute(name = "sourcename")
    @XmlSchemaType(name = "anySimpleType")
    protected String sourcename;

    /**
     * Gets the value of the b034 property.
     * 
     * @return
     *     possible object is
     *     {@link B034 }
     *     
     */
    public B034 getB034() {
        return b034;
    }

    /**
     * Sets the value of the b034 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B034 }
     *     
     */
    public void setB034(B034 value) {
        this.b034 = value;
    }

    /**
     * Gets the value of the b035 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the b035 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getB035().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link B035 }
     * 
     * 
     */
    public List<B035> getB035() {
        if (b035 == null) {
            b035 = new ArrayList<B035>();
        }
        return this.b035;
    }

    /**
     * Gets the value of the x412 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the x412 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getX412().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link X412 }
     * 
     * 
     */
    public List<X412> getX412() {
        if (x412 == null) {
            x412 = new ArrayList<X412>();
        }
        return this.x412;
    }

    /**
     * Gets the value of the x413 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the x413 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getX413().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link X413 }
     * 
     * 
     */
    public List<X413> getX413() {
        if (x413 == null) {
            x413 = new ArrayList<X413>();
        }
        return this.x413;
    }

    /**
     * Gets the value of the x414 property.
     * 
     * @return
     *     possible object is
     *     {@link X414 }
     *     
     */
    public X414 getX414() {
        return x414;
    }

    /**
     * Sets the value of the x414 property.
     * 
     * @param value
     *     allowed object is
     *     {@link X414 }
     *     
     */
    public void setX414(X414 value) {
        this.x414 = value;
    }

    /**
     * Gets the value of the nameidentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameidentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNameidentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Nameidentifier }
     * 
     * 
     */
    public List<Nameidentifier> getNameidentifier() {
        if (nameidentifier == null) {
            nameidentifier = new ArrayList<Nameidentifier>();
        }
        return this.nameidentifier;
    }

    /**
     * Gets the value of the b036 property.
     * 
     * @return
     *     possible object is
     *     {@link B036 }
     *     
     */
    public B036 getB036() {
        return b036;
    }

    /**
     * Sets the value of the b036 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B036 }
     *     
     */
    public void setB036(B036 value) {
        this.b036 = value;
    }

    /**
     * Gets the value of the b037 property.
     * 
     * @return
     *     possible object is
     *     {@link B037 }
     *     
     */
    public B037 getB037() {
        return b037;
    }

    /**
     * Sets the value of the b037 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B037 }
     *     
     */
    public void setB037(B037 value) {
        this.b037 = value;
    }

    /**
     * Gets the value of the b038 property.
     * 
     * @return
     *     possible object is
     *     {@link B038 }
     *     
     */
    public B038 getB038() {
        return b038;
    }

    /**
     * Sets the value of the b038 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B038 }
     *     
     */
    public void setB038(B038 value) {
        this.b038 = value;
    }

    /**
     * Gets the value of the b039 property.
     * 
     * @return
     *     possible object is
     *     {@link B039 }
     *     
     */
    public B039 getB039() {
        return b039;
    }

    /**
     * Sets the value of the b039 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B039 }
     *     
     */
    public void setB039(B039 value) {
        this.b039 = value;
    }

    /**
     * Gets the value of the b247 property.
     * 
     * @return
     *     possible object is
     *     {@link B247 }
     *     
     */
    public B247 getB247() {
        return b247;
    }

    /**
     * Sets the value of the b247 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B247 }
     *     
     */
    public void setB247(B247 value) {
        this.b247 = value;
    }

    /**
     * Gets the value of the b040 property.
     * 
     * @return
     *     possible object is
     *     {@link B040 }
     *     
     */
    public B040 getB040() {
        return b040;
    }

    /**
     * Sets the value of the b040 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B040 }
     *     
     */
    public void setB040(B040 value) {
        this.b040 = value;
    }

    /**
     * Gets the value of the b041 property.
     * 
     * @return
     *     possible object is
     *     {@link B041 }
     *     
     */
    public B041 getB041() {
        return b041;
    }

    /**
     * Sets the value of the b041 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B041 }
     *     
     */
    public void setB041(B041 value) {
        this.b041 = value;
    }

    /**
     * Gets the value of the b248 property.
     * 
     * @return
     *     possible object is
     *     {@link B248 }
     *     
     */
    public B248 getB248() {
        return b248;
    }

    /**
     * Sets the value of the b248 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B248 }
     *     
     */
    public void setB248(B248 value) {
        this.b248 = value;
    }

    /**
     * Gets the value of the b042 property.
     * 
     * @return
     *     possible object is
     *     {@link B042 }
     *     
     */
    public B042 getB042() {
        return b042;
    }

    /**
     * Sets the value of the b042 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B042 }
     *     
     */
    public void setB042(B042 value) {
        this.b042 = value;
    }

    /**
     * Gets the value of the b043 property.
     * 
     * @return
     *     possible object is
     *     {@link B043 }
     *     
     */
    public B043 getB043() {
        return b043;
    }

    /**
     * Sets the value of the b043 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B043 }
     *     
     */
    public void setB043(B043 value) {
        this.b043 = value;
    }

    /**
     * Gets the value of the b047 property.
     * 
     * @return
     *     possible object is
     *     {@link B047 }
     *     
     */
    public B047 getB047() {
        return b047;
    }

    /**
     * Sets the value of the b047 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B047 }
     *     
     */
    public void setB047(B047 value) {
        this.b047 = value;
    }

    /**
     * Gets the value of the x443 property.
     * 
     * @return
     *     possible object is
     *     {@link X443 }
     *     
     */
    public X443 getX443() {
        return x443;
    }

    /**
     * Sets the value of the x443 property.
     * 
     * @param value
     *     allowed object is
     *     {@link X443 }
     *     
     */
    public void setX443(X443 value) {
        this.x443 = value;
    }

    /**
     * Gets the value of the alternativename property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alternativename property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlternativename().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Alternativename }
     * 
     * 
     */
    public List<Alternativename> getAlternativename() {
        if (alternativename == null) {
            alternativename = new ArrayList<Alternativename>();
        }
        return this.alternativename;
    }

    /**
     * Gets the value of the contributordate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contributordate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContributordate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Contributordate }
     * 
     * 
     */
    public List<Contributordate> getContributordate() {
        if (contributordate == null) {
            contributordate = new ArrayList<Contributordate>();
        }
        return this.contributordate;
    }

    /**
     * Gets the value of the professionalaffiliation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the professionalaffiliation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProfessionalaffiliation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Professionalaffiliation }
     * 
     * 
     */
    public List<Professionalaffiliation> getProfessionalaffiliation() {
        if (professionalaffiliation == null) {
            professionalaffiliation = new ArrayList<Professionalaffiliation>();
        }
        return this.professionalaffiliation;
    }

    /**
     * Gets the value of the b044 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the b044 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getB044().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link B044 }
     * 
     * 
     */
    public List<B044> getB044() {
        if (b044 == null) {
            b044 = new ArrayList<B044>();
        }
        return this.b044;
    }

    /**
     * Gets the value of the website property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the website property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWebsite().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Website }
     * 
     * 
     */
    public List<Website> getWebsite() {
        if (website == null) {
            website = new ArrayList<Website>();
        }
        return this.website;
    }

    /**
     * Gets the value of the b048 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the b048 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getB048().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link B048 }
     * 
     * 
     */
    public List<B048> getB048() {
        if (b048 == null) {
            b048 = new ArrayList<B048>();
        }
        return this.b048;
    }

    /**
     * Gets the value of the b249 property.
     * 
     * @return
     *     possible object is
     *     {@link B249 }
     *     
     */
    public B249 getB249() {
        return b249;
    }

    /**
     * Sets the value of the b249 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B249 }
     *     
     */
    public void setB249(B249 value) {
        this.b249 = value;
    }

    /**
     * Gets the value of the contributorplace property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contributorplace property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContributorplace().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Contributorplace }
     * 
     * 
     */
    public List<Contributorplace> getContributorplace() {
        if (contributorplace == null) {
            contributorplace = new ArrayList<Contributorplace>();
        }
        return this.contributorplace;
    }

    /**
     * Gets the value of the refname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefname() {
        return refname;
    }

    /**
     * Sets the value of the refname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefname(String value) {
        this.refname = value;
    }

    /**
     * Gets the value of the shortname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortname(String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the datestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatestamp() {
        return datestamp;
    }

    /**
     * Sets the value of the datestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatestamp(String value) {
        this.datestamp = value;
    }

    /**
     * Gets the value of the sourcetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcetype() {
        return sourcetype;
    }

    /**
     * Sets the value of the sourcetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcetype(String value) {
        this.sourcetype = value;
    }

    /**
     * Gets the value of the sourcename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcename() {
        return sourcename;
    }

    /**
     * Sets the value of the sourcename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcename(String value) {
        this.sourcename = value;
    }

}
